In [1]:
import numpy as np

In [3]:
np.random.rand() #btw 0 and 1 #uniform distributions

0.7167684031277249

In [4]:
np.random.rand(3)

array([0.4618799 , 0.52822614, 0.4575637 ])

In [5]:
np.random.rand(2, 2)

array([[0.87215645, 0.75364289],
       [0.06357863, 0.20134669]])

In [8]:
np.random.randn(2,2) #mean=0 and std=1

array([[ 0.29278704,  1.08508294],
       [ 0.39352543, -0.39697253]])

In [14]:
np.random.randint(1, 7, size=(2,3))

array([[4, 4, 2],
       [6, 5, 3]])

In [19]:
np.random.seed(43) #locks the randomness
print(np.random.rand(3))

[0.11505457 0.60906654 0.13339096]


In [30]:
names = ["Ajay", "Vijay", "Bob"]
np.random.choice(names, size=2, p=[0.8, 0.1, 0.1])

array(['Bob', 'Ajay'], dtype='<U5')

In [31]:
arr = np.array([1,2,3,4,5,6])
np.random.shuffle(arr)

In [32]:
print(arr) #in place

[3 6 4 2 5 1]
