In [1]:
import numpy as np

In [2]:
arr = np.array([10, 20, 30, 40, 50])

In [47]:
condition = arr > 25
condition

array([False, False,  True,  True,  True])

In [48]:
arr[condition]

array([30, 40, 50])

In [49]:
arr[arr > 25]

array([30, 40, 50])

In [63]:
arr2d = np.array([[5, 100, 15], [20, 25, 30]])

arr2d[arr2d > 15]

array([100,  20,  25,  30])

In [64]:
arr2d[(arr2d > 10) & (arr2d < 40) ]

array([15, 20, 25, 30])

In [65]:
#select specific elements from our array

In [66]:
arr = np.array([10, 20, 30, 40, 50])

arr[list of row/dim1 indices, list of col/dim2 indices, list of dim3 indices....]

In [68]:
arr[[1,3,4]]

array([20, 40, 50])

In [69]:
arr2d

array([[  5, 100,  15],
       [ 20,  25,  30]])

In [70]:
arr2d[[1,0], [0,2]]

array([20, 15])