In [9]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20, 30, 40])

In [10]:
#element wise addition

In [11]:
arr1 * arr2

ValueError: operands could not be broadcast together with shapes (5,) (4,) 

In [12]:
arr1 + 5

array([ 6,  7,  8,  9, 10])

In [14]:
arr1 + np.array([5,5,5,5,5]) #broadcasting

array([ 6,  7,  8,  9, 10])

In [15]:
arr1

array([1, 2, 3, 4, 5])

In [19]:
print(np.sqrt(arr1)) #math -> for loop
print(np.exp(arr1))
print(np.log(arr1))
print(np.sin(arr1))

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [ ]:
#no loops required
#functions are vectorized -> automatically apply to all elements with the end of for loop

In [21]:
arr2
arr1 = np.array([1,2,3,4])

In [22]:
arr2 // arr1

array([10, 10, 10, 10])

In [24]:
arr1 % arr2

array([1, 2, 3, 4])