In [3]:
import numpy as np

In [4]:
arr = np.array([10, 20, 30, 40, 50])

In [ ]:
index ->  0

In [5]:
arr[2]

30

In [6]:
arr[-1]

50

In [ ]:
#slice notation

[start: stop: step]

In [7]:
arr

array([10, 20, 30, 40, 50])

In [8]:
arr[0:2]

array([10, 20])

In [9]:
arr[2::2]

array([30, 50])

In [11]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])

In [13]:
arr2d[1][1]

5

In [14]:
arr2d[1,1] #1st dim at index 1 and for  2nd dim at index 1

5

In [15]:
arr2d[0, 2]

3

In [16]:
arr2d[0:2,1:]

array([[2, 3],
       [5, 6]])

In [17]:
arr3d = np.array([
    [[1, 2], [3, 4]], 
    [[5, 6], [7, 8]]
])

In [18]:
arr3d[0,1,1] #3 arguments for 3 dim

4

In [ ]:
# it returns a view and not a copy

In [19]:
arr = np.array([10, 20, 30, 40, 50])
slice_arr = arr[1:5]

In [20]:
slice_arr

array([20, 30, 40, 50])

In [21]:
slice_arr[1] = 300

In [22]:
slice_arr

array([ 20, 300,  40,  50])

In [23]:
arr

array([ 10,  20, 300,  40,  50])