In [1]:
import numpy as np

In [9]:
marks = np.array([85, 90, 75, 60]) #Aryan

In [10]:
np.sum(marks)

310

In [11]:
np.mean(marks)

77.5

In [12]:
np.max(marks)

90

In [13]:
np.min(marks)

60

In [14]:
marks_2d = np.array([
    [85, 90, 75, 60],
    [70, 80, 65, 85],
    [95, 88, 92, 75]
])

#1st dim students
#2nd dim subject

In [15]:
np.sum(marks_2d)

960

In [16]:
np.sum(marks_2d, axis=0) #sum of marks per subject

array([250, 258, 232, 220])

In [ ]:
#axis = 0 -> 1st dim -> collapsing row wise  -> operate down the cols

In [17]:
np.sum(marks_2d, axis=1) #sum of marks per student

#axis=1 -> 2nd dim -> collapse 2nd dim (cols) -> operate across rows

array([310, 300, 350])

In [20]:
marks_3d = np.array([
    [
        [80, 85, 90, 75],   # Class 1, Student 1
        [70, 88, 78, 85],   # Class 1, Student 2
        [95, 92, 85, 80]    # Class 1, Student 3
    ],
    [
        [65, 75, 80, 70],   # Class 2, Student 1
        [88, 82, 90, 84],   # Class 2, Student 2
        [78, 85, 88, 91]    # Class 2, Student 3
    ]
])

In [19]:
#average marks per student across all subjects in each class

In [21]:
np.mean(marks_3d,axis=2)

array([[82.5 , 80.25, 88.  ],
       [72.5 , 86.  , 85.5 ]])

In [ ]:
#overall average per subject across all students and classes

subject1 = 100

collapse -> class and student (0,1)

In [22]:
np.mean(marks_3d, axis=(0,1))

array([79.33333333, 84.5       , 85.16666667, 80.83333333])