In [ ]:
ndarray -> n dim array, homogeneous 

ndarray -> class

In [22]:
import numpy as np

array_1d = np.array(["Ravi", "Aryan", "Keya", 3])

In [23]:
type(array_1d)

numpy.ndarray

In [24]:
array_1d

array(['Ravi', 'Aryan', 'Keya', '3'], dtype='<U11')

In [8]:
array_1d.ndim

1

In [ ]:
#save the marks of students in 3 subjects

In [9]:
marks = np.array([
    [90, 85, 88], #Ravi
    [100, 98, 100], #aryan
    [33, 56, 90] #keys
])

In [10]:
type(marks)

numpy.ndarray

In [11]:
marks

array([[ 90,  85,  88],
       [100,  98, 100],
       [ 33,  56,  90]])

In [ ]:
3 dimensions-> students
subject
exam scores

In [12]:
marks_3d = np.array([
    [
        [20, 30, 56], #math
        [56, 89, 100], #science
        [100, 100, 100] #english
    ],
    [
        [34, 78, 90], #math
        [45, 67, 90], #science
        [55, 89, 100] #english
    ]
])

In [13]:
marks_3d

array([[[ 20,  30,  56],
        [ 56,  89, 100],
        [100, 100, 100]],

       [[ 34,  78,  90],
        [ 45,  67,  90],
        [ 55,  89, 100]]])

In [17]:
x = np.zeros((6))

In [18]:
x

array([0., 0., 0., 0., 0., 0.])

In [19]:
x.ndim

1

In [20]:
x.shape

(6,)

In [21]:
x.dtype

dtype('float64')

In [25]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [26]:
np.full((2,2), 7)

array([[7, 7],
       [7, 7]])

In [27]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [28]:
#evenly spaced numbers

np.linspace(0,1, 5) # create 5 numbers btw 0 and 1 (both 0 and 1 are inclusive)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [29]:
np.random.rand(2, 3, 5) #random numners btw 0 and 1

array([[[0.64901978, 0.15204522, 0.39697845, 0.27557022, 0.2534815 ],
        [0.0467509 , 0.89882802, 0.98868706, 0.32099495, 0.79622393],
        [0.31628874, 0.00321551, 0.00973955, 0.4360293 , 0.5562149 ]],

       [[0.85773279, 0.94890812, 0.19167748, 0.64230884, 0.34363986],
        [0.79916005, 0.11891453, 0.74794786, 0.35781396, 0.89768431],
        [0.0116458 , 0.62026796, 0.23673433, 0.54564331, 0.60131949]]])

In [35]:
y = np.array([1,2,3], dtype='float32')

In [36]:
y.ndim

1

In [37]:
y.shape

(3,)

In [38]:
y.dtype

dtype('float32')

In [39]:
y

array([1., 2., 3.], dtype=float32)