In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3])
print(arr)
print(type(arr))

[1 2 3]
<class 'numpy.ndarray'>


In [3]:
arr.dtype

dtype('int32')

In [4]:
arr = np.array([1, 2, 3], dtype='float32')
print(arr)
print(arr.dtype)

[1. 2. 3.]
float32


In [5]:
arr = np.array([1, 2, 3])
new_arr = arr.astype('float64')
print(arr)
print(new_arr)

[1 2 3]
[1. 2. 3.]


In [6]:
a = np.array([1, 2.5, 'hello'])

In [7]:
a

array(['1', '2.5', 'hello'], dtype='<U32')

In [ ]:
type promotion